# Collector specific configuration
base_url: "https://hqfao-hub.maps.arcgis.com"
feature_table_id: "98265cbe82e344f88552d4c2d3615c3c"

description: Latest biweekly insights on flood events and their impacts on various land cover types for (country)
title: FAO Events Visualization in Emergencies (EVE) system
resource_title: Events Visualization in Emergencies

tags:
  - climate hazards
  - flooding
  - environment

hxl_tags:
  "adm0_iso3": "#country+code"
  "adm0_name": "#country+name"
  "admin_level": "#adm+level"
  "adm1_pcode": "#adm1+code"
  "adm1_name": "#adm1+name"
  "adm2_pcode": "#adm2+code"
  "adm2_name": "#adm2+name"
  "period_number": "#period+num"
  "start_date": "#date+start"
  "biweekly_group": "#date+period"
  "cropland_flooded_sq_km": "#land+flooded+agri+area+km2"
  "cropland_flooded_ha": "#land+flooded+agri+area+ha"
  "total_area_flooded_sq_km": "#land+flooded+area+km2"
  "total_area_flooded_ha": "#land+flooded+area+ha"
  "perc_cropland_flooded": "#land+flooded+agri+perc"
  "perc_total_area_flooded": "#land+flooded+perc"
  "pop_affected": "#population+affected"
  "end_date": "#date+end"
