# This workflow will install Python dependencies, lint and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  workflow_dispatch: # add run button in github
  push:
    branches-ignore:
      - gh-pages
      - 'dependabot/**'
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Kerberos development libraries
      run: sudo apt-get update && sudo apt-get install -y libkrb5-dev
    - name: Install Hatch
      uses: pypa/hatch@install
    - name: Test with hatch/pytest
      env:
        DIEM_USERNAME: ${{ secrets.DIEM_USERNAME }}
        DIEM_PASSWORD: ${{ secrets.DIEM_PASSWORD }}
        HDX_KEY_TEST: ${{ secrets.HDX_BOT_SCRAPERS_API_TOKEN }}
        GSHEET_AUTH: ${{ secrets.GSHEET_AUTH }}
      run: |
        hatch test
    - name: Check styling
      if: always()
      run: |
        hatch fmt --check
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        junit_files: test-results.xml
    - name: Publish in Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: tests
        format: lcov
